import { jsPDF } from "jspdf";
import { COLOR_SWATCHES } from "@/data/event-questionnaire";
import type { QState } from "@/data/questionnaire-q-state";

const MM_PAGE_H = 297;
const MARGIN = 16;
const LINE = 5.2;
const FOOTER_H = 22;

export type CartLine = { label: string; amount: number };

async function fetchDataUrl(path: string): Promise<string | null> {
  try {
    const res = await fetch(path);
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const r = new FileReader();
      r.onloadend = () => resolve(r.result as string);
      r.onerror = reject;
      r.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function paletteText(ids: string[]) {
  if (!ids.length) return "—";
  return ids
    .map((id) => {
      const c = COLOR_SWATCHES.find((x) => x.id === id);
      if (!c) return id;
      if (c.id === "mixed") return `${c.label} (multi-tone)`;
      return `${c.label} (${c.hex})`;
    })
    .join("; ");
}

function ensureSpace(doc: jsPDF, y: number, need: number): number {
  if (y + need > MM_PAGE_H - MARGIN - FOOTER_H) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function writeBlock(doc: jsPDF, title: string, body: string, y: number, pageW: number): number {
  const maxW = pageW - 2 * MARGIN;
  y = ensureSpace(doc, y, LINE * 4);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(55, 48, 40);
  doc.text(title, MARGIN, y);
  y += LINE;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(40, 38, 35);
  const lines = doc.splitTextToSize(body || "—", maxW);
  for (const line of lines) {
    y = ensureSpace(doc, y, LINE);
    doc.text(line, MARGIN, y);
    y += LINE * 0.95;
  }
  y += LINE * 0.35;
  return y;
}

function drawFooter(doc: jsPDF, pageW: number, pageNum: number, totalPages: number) {
  const y = MM_PAGE_H - MARGIN - 2;
  doc.setFontSize(7);
  doc.setTextColor(110, 100, 90);
  doc.setFont("helvetica", "normal");
  const footerLines = doc.splitTextToSize(
    `This PDF was generated by the Kamelia website — Event Styling Questionnaire. © ${new Date().getFullYear()} Kamelia. All rights reserved. Indicative pricing only; final quote after studio consultation.`,
    pageW - 2 * MARGIN,
  );
  const yy = y - (footerLines.length - 1) * 3.2;
  doc.text(footerLines, MARGIN, yy);
  doc.text(`Page ${pageNum} / ${totalPages}`, pageW - MARGIN, y, { align: "right" });
}

/** Build questionnaire brief PDF; returns Blob for optional reuse. */
export async function buildQuestionnairePdfBlob(
  s: QState,
  cartLines: CartLine[],
  total: number,
  formatRs: (n: number) => string,
): Promise<Blob> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  let y = MARGIN;

  const logoData = await fetchDataUrl("/logo_black.png");
  if (logoData) {
    try {
      doc.addImage(logoData, "PNG", MARGIN, y, 42, 11);
    } catch {
      /* ignore bad image */
    }
    y += 16;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(35, 30, 25);
  doc.text("Kamelia — The Floral Designer", MARGIN, y);
  y += LINE * 1.4;
  doc.setFontSize(11);
  doc.setTextColor(140, 115, 70);
  doc.text("Event Styling Questionnaire", MARGIN, y);
  y += LINE * 1.2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(90, 85, 78);
  doc.text(`Generated: ${new Date().toLocaleString("en-MU", { dateStyle: "medium", timeStyle: "short" })}`, MARGIN, y);
  y += LINE * 2;

  doc.setDrawColor(190, 170, 130);
  doc.line(MARGIN, y, pageW - MARGIN, y);
  y += LINE * 1.2;

  y = writeBlock(
    doc,
    "1. Event & venue",
    [
      `Event type: ${s.eventType || "—"}`,
      `Date: ${s.eventDate || "—"}`,
      `Venue: ${s.venueName || "—"}  Setting: ${s.venueSetting || "—"}  City/region: ${s.city || "—"}`,
      `Guest count: ${s.guestCount || "—"}`,
    ].join("\n"),
    y,
    pageW,
  );

  y = writeBlock(
    doc,
    "2. Design",
    [
      `Theme style: ${s.themeStyle || "—"}`,
      `Color palette: ${paletteText(s.colors)}`,
      `Floral preferences: ${s.floralPrefs.length ? s.floralPrefs.join(", ") : "—"}`,
    ].join("\n"),
    y,
    pageW,
  );

  y = writeBlock(
    doc,
    "3. Stage",
    [`Stage type: ${s.stageType || "—"}`].join("\n"),
    y,
    pageW,
  );

  y = writeBlock(
    doc,
    "4. Budget & inspiration",
    [`Budget range: ${s.budget || "—"}`, `Inspiration links:\n${s.inspirationLinks || "—"}`, `Notes:\n${s.notes || "—"}`].join(
      "\n\n",
    ),
    y,
    pageW,
  );

  y = writeBlock(
    doc,
    "5. Contact",
    [`Name: ${s.fullName || "—"}`, `Phone: ${s.phone || "—"}`, `WhatsApp: ${s.whatsapp || "—"}`, `Email: ${s.email || "—"}`].join(
      "\n",
    ),
    y,
    pageW,
  );

  y = ensureSpace(doc, y, LINE * (cartLines.length + 6));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(55, 48, 40);
  doc.text("Indicative pricing (sample Rs)", MARGIN, y);
  y += LINE * 1.2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(40, 38, 35);
  for (const line of cartLines) {
    y = ensureSpace(doc, y, LINE);
    doc.text(line.label.slice(0, 85), MARGIN, y);
    doc.text(`Rs ${formatRs(line.amount)}`, pageW - MARGIN - 2, y, { align: "right" });
    y += LINE * 0.95;
  }
  y += LINE * 0.4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Estimated total", MARGIN, y);
  doc.setTextColor(140, 115, 70);
  doc.text(`Rs ${formatRs(total)}`, pageW - MARGIN - 2, y, { align: "right" });
  doc.setTextColor(40, 38, 35);
  y += LINE * 2;

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawFooter(doc, pageW, p, totalPages);
  }

  return doc.output("blob");
}

export function defaultPdfFilename() {
  const d = new Date();
  const stamp = d.toISOString().slice(0, 10);
  return `kamelia-event-brief-${stamp}.pdf`;
}

/** WhatsApp deep link — user must attach the PDF manually in the chat composer. */
export function buildWhatsappSendPdfHref(s: QState, fallbackDigits: string): string {
  const raw = (s.whatsapp || s.phone || fallbackDigits).replace(/\D/g, "");
  const num = raw.length ? raw : fallbackDigits.replace(/\D/g, "");
  const name = s.fullName?.trim() || "Client";
  const email = s.email?.trim() || "";
  const text = [
    `Hi Kamelia,`,
    ``,
    `I'm sending my completed *Event Styling Questionnaire* as a PDF.`,
    ``,
    `📎 *Please attach your PDF in WhatsApp before sending:*`,
    `• Mobile: tap **+** or **📎** → **Document** → choose the downloaded file (e.g. ${defaultPdfFilename()}).`,
    `• WhatsApp Web / Desktop: click the **paperclip** → **Document** → select the PDF from your Downloads folder.`,
    ``,
    `If you haven't generated the PDF yet, go back to the form on the website and tap **Generate my vision** first.`,
    ``,
    `— ${name}${email ? ` · ${email}` : ""}`,
  ].join("\n");
  return `https://wa.me/${num}?text=${encodeURIComponent(text)}`;
}
